
SET FOREIGN_KEY_CHECKS = 0; 
TRUNCATE TABLE coursebranch;
TRUNCATE TABLE coursecontent;
TRUNCATE TABLE coursedepartment;
TRUNCATE TABLE courses;
TRUNCATE TABLE organisation;
TRUNCATE TABLE user;
TRUNCATE TABLE userroles;
SET FOREIGN_KEY_CHECKS = 1; 

